# # -*- coding: utf-8 -*-
# """LipNet.ipynb

# Automatically generated by Colab.

# Original file is located at
#     https://colab.research.google.com/drive/1V1FYKkllijmBDKWsnUa7-hGJLTlv6UVH

# # Installing and Importing Dependencies
# """



# import os
# import cv2
# import tensorflow as tf
# import numpy as np
# import matplotlib.pyplot as plt
# from typing import List
# import imageio

# """# Setting memory growth rate for GPU (for training in colab, to avoid out of memory error):"""

# physical_devices = tf.config.list_physical_devices('GPU')
# try:
#     tf.config.experimental.set_memory_growth(physical_devices[0], True)
# except:
#     pass

# """# Building the Data Loading Function:"""

# import gdown

# url = 'https://drive.google.com/uc?id=1YlvpDLix3S-U8fd-gqRwPcWXAXm8JwjL'
# output = 'data.zip'
# gdown.download(url, output, quiet = False)
# gdown.extractall('data.zip')

# def load_video(path:str) -> List[float]:

#     cap = cv2.VideoCapture(path)
#     frames = []
#     for _ in range(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))):
#         ret, frame = cap.read()
#         frame = tf.image.rgb_to_grayscale(frame)
#         frames.append(frame[190:236,80:220,:])
#     cap.release()

#     mean = tf.math.reduce_mean(frames)
#     std = tf.math.reduce_std(tf.cast(frames, tf.float32))
#     return tf.cast((frames - mean), tf.float32) / std

# vocab = [x for x in "abcdefghijklmnopqrstuvwxyz'?!123456789 "]

# char_to_num = tf.keras.layers.StringLookup(vocabulary=vocab, oov_token="")
# num_to_char = tf.keras.layers.StringLookup(vocabulary=char_to_num.get_vocabulary(), oov_token="", invert=True)

# print(
#     f"the vocabulary is: {char_to_num.get_vocabulary()}"
#     f"(size = {char_to_num.vocabulary_size()})"
# )

# char_to_num(['a','a','r','a','n','a','y'])

# def load_alignments(path:str) -> List[str]:
#     with open(path, 'r') as f:
#         lines = f.readlines()
#     tokens = []
#     for line in lines:
#         line = line.split()
#         if line[2] != 'sil':
#             tokens = [*tokens,' ', line[2]]
#     return char_to_num(tf.reshape(tf.strings.unicode_split(tokens, input_encoding='UTF-8'), (-1)))[1:]
# def load_data(path: str):
#     path = path.numpy().decode('utf-8')

#     # Windows safe filename extraction
#     file_name = path.split('/')[-1].split('\\')[-1].split('.')[0]

#     video_path = f'data/s1/{file_name}.mpg'
#     alignment_path = f'data/alignments/s1/{file_name}.align'

#     print("DEBUG file_name:", file_name)  # you can remove later

#     frames = load_video(video_path)
#     alignments = load_alignments(alignment_path)

#     return frames, alignments

# # def load_data(path: str):
# #     path = path.numpy().decode('utf-8')  # decode tensor to string
# #     path = path.replace('\\', '/')       # normalize Windows paths

# #     file_name = os.path.splitext(os.path.basename(path))[0]

# #     video_path = os.path.join('data', 's1', f'{file_name}.mpg')
# #     alignment_path = os.path.join('data', 'alignments', 's1', f'{file_name}.align')

# #     frames = load_video(video_path)
# #     alignments = load_alignments(alignment_path)

# #     return frames, alignments

# # def load_data(path: str):
# #     path = bytes.decode(path.numpy())
# #     file_name = os.path.splitext(os.path.basename(path))[0]
# #     # File name splitting for windows
# #     #file_name = path.split('\\')[-1].split('.')[0]
# #     video_path = os.path.join('data','s1',f'{file_name}.mpg')
# #     alignment_path = os.path.join('data','alignments','s1',f'{file_name}.align')
# #     frames = load_video(video_path)
# #     alignments = load_alignments(alignment_path)

# #     return frames, alignments

# test_path = './data/s1/bbal6n.mpg'

# tf.convert_to_tensor(test_path).numpy().decode('UTF-8').split('/')[-1].split('.')

# frames, alignments = load_data(tf.convert_to_tensor(test_path))

# plt.imshow(frames[0])

# tf.strings.reduce_join([bytes.decode(x) for x in num_to_char(alignments.numpy()).numpy()])

# def mappable_function(path:str) ->List[str]:
#     result = tf.py_function(load_data, [path], (tf.float32, tf.int64))
#     return result

# """# Creating Data Pipeline"""

# data = tf.data.Dataset.list_files('./data/s1/*.mpg')
# data = data.shuffle(500, reshuffle_each_iteration=False)
# data = data.map(mappable_function)
# data = data.padded_batch(2, padded_shapes=([75, None, None, None], [40]))
# data = data.prefetch(tf.data.AUTOTUNE)
# #split for training and testing:
# train = data.take(450)
# test = data.skip(450)

# frames, alignments = data.as_numpy_iterator().next()

# len(frames)

# test = data.as_numpy_iterator()

# val = test.next(); val[0]

# imageio.mimsave('./animation.gif', val[0][0].squeeze(), fps=10)

# plt.imshow(val[0][0][35])
# # here the first zero is videos
# # the second zero is 1st video out of the batch
# # third zero says return the first frame in the video

# tf.strings.reduce_join([num_to_char(word) for word in val[1][0]])

# """# Designing the neural network"""

# from tensorflow.keras.models import Sequential
# from tensorflow.keras.layers import Conv3D, LSTM, Dense, Dropout, Bidirectional, MaxPool3D, Activation, Reshape, SpatialDropout3D, BatchNormalization, TimeDistributed, Flatten
# from tensorflow.keras.optimizers import Adam
# from tensorflow.keras.callbacks import ModelCheckpoint, LearningRateScheduler, TensorBoard

# model = Sequential()
# model.add(Conv3D(128, 3, input_shape=(75,46,140,1), padding = 'same'))
# model.add(Activation('relu'))
# model.add(MaxPool3D((1,2,2)))

# model.add(Conv3D(256, 3, padding = 'same'))
# model.add(Activation('relu'))
# model.add(MaxPool3D((1,2,2)))

# model.add(Conv3D(75, 3, padding = 'same'))
# model.add(Activation('relu'))
# model.add(MaxPool3D((1,2,2)))

# model.add(TimeDistributed(Flatten()))

# model.add(Bidirectional(LSTM(128, kernel_initializer='Orthogonal', return_sequences=True)))
# model.add(Dropout(0.5))

# model.add(Bidirectional(LSTM(128, kernel_initializer='Orthogonal', return_sequences=True)))
# model.add(Dropout(0.5))

# model.add(Dense(char_to_num.vocabulary_size()+1, kernel_initializer='he_normal', activation='softmax'))

# model.summary()

# y_hat = model.predict(val[0])

# tf.strings.reduce_join([num_to_char(x) for x in tf.argmax(y_hat[0], axis = 1)])

# tf.strings.reduce_join([num_to_char(tf.argmax(x)) for x in y_hat[0]])

# model.input_shape

# model.output_shape

# """# Setting Up Training Options and Training"""

# def scheduler(epoch, lr):
#   if epoch < 30:
#     return lr #returns the same learning rate
#   else:
#     return lr * tf.math.exp(-0.1) #If the epoch is 30 or greater, it returns the learning rate multiplied by tf.math.exp(-0.1) (approximately 0.9), effectively decreasing the learning rate.

# def CTCLoss(y_true, y_pred):
#     batch_len = tf.cast(tf.shape(y_true)[0], dtype="int64")
#     input_length = tf.cast(tf.shape(y_pred)[1], dtype="int64")
#     label_length = tf.cast(tf.shape(y_true)[1], dtype="int64")

#     input_length = input_length * tf.ones(shape=(batch_len, 1), dtype="int64")
#     label_length = label_length * tf.ones(shape=(batch_len, 1), dtype="int64")

#     loss = tf.keras.backend.ctc_batch_cost(y_true, y_pred, input_length, label_length)
#     return loss

# class ProduceExample(tf.keras.callbacks.Callback):
#     def __init__(self, dataset) -> None:
#         self.dataset = dataset.as_numpy_iterator()

#     def on_epoch_end(self, epoch, logs=None) -> None:
#         data = self.dataset.next()
#         yhat = self.model.predict(data[0])
#         decoded = tf.keras.backend.ctc_decode(yhat, [75,75], greedy=False)[0][0].numpy()
#         for x in range(len(yhat)):
#             print('Original:', tf.strings.reduce_join(num_to_char(data[1][x])).numpy().decode('utf-8'))
#             print('Prediction:', tf.strings.reduce_join(num_to_char(decoded[x])).numpy().decode('utf-8'))
#             print('~'*100)

# # model.compile(optimizer = tf.keras.optimizers.legacy.Adam(learning_rate = 0.0001), loss = CTCLoss)

# # checkpoint_callback = ModelCheckpoint(os.path.join('models', 'checkpoint'), monitor = 'loss', save_weights_only = True)

# # schedule_callback = LearningRateScheduler(scheduler)

# # example_callback = ProduceExample(data)

# # model.fit(train, validation_data=test, epochs=100, callbacks=[checkpoint_callback, schedule_callback, example_callback])

# """# Making a prediction"""

# #Loading the checkpoints for the model
# # in order to avoid the delay in training, I'm leveraging the already trained weights up till the 96th epoch from a github repo
# url = 'https://drive.google.com/uc?id=1vWscXs4Vt0a_1IH1-ct2TCgXAZT-N3_Y'
# output = 'checkpoints.zip'
# gdown.download(url, output, quiet=False)
# gdown.extractall('checkpoints.zip', 'models')

# model.load_weights('models/checkpoint')

# test_data = test

# test_data.next()

# sample = test_data.next()

# yhat = model.predict(sample[0])

# # print('~'*100, 'REAL TEXT')
# # [tf.strings.reduce_join([num_to_char(word) for word in sentence]) for sentence in sample[1]]

# # decoded = tf.keras.backend.ctc_decode(yhat, input_length=[75,75], greedy=True)[0][0].numpy()

# # print('~'*100, 'PREDICTIONS')
# # [tf.strings.reduce_join([num_to_char(word) for word in sentence]) for sentence in decoded]
# print('\n' + '~'*100 + ' REAL TEXT')
# for sentence in sample[1]:
#     print(tf.strings.reduce_join(num_to_char(sentence)).numpy().decode('utf-8'))

# decoded = tf.keras.backend.ctc_decode(yhat, input_length=[75,75], greedy=True)[0][0].numpy()

# print('\n' + '~'*100 + ' PREDICTIONS')
# for sentence in decoded:
#     print(tf.strings.reduce_join(num_to_char(sentence)).numpy().decode('utf-8'))


# """# Testing on a video"""

# sample = load_data(tf.convert_to_tensor('data/s1/bbal8p.mpg'))

# yhat = model.predict(tf.expand_dims(sample[0], axis = 0))

# yhat.shape

# # print('~'*100, 'REAL TEXT')
# # [tf.strings.reduce_join([num_to_char(word) for word in sentence]) for sentence in [sample[1]]]
# print('\n' + '~'*100 + ' REAL TEXT')
# print(tf.strings.reduce_join(num_to_char(sample[1])).numpy().decode('utf-8'))


# decoded = tf.keras.backend.ctc_decode(yhat, input_length=[75], greedy=True)[0][0].numpy()

# # print('~'*100, 'PREDICTIONS')
# # [tf.strings.reduce_join([num_to_char(word) for word in sentence]) for sentence in decoded]
# print('\n' + '~'*100 + ' PREDICTIONS')
# for sentence in decoded:
#     print(tf.strings.reduce_join(num_to_char(sentence)).numpy().decode('utf-8'))


# import os
# import cv2
# import tensorflow as tf
# import numpy as np

# # ---------------- CONFIG ----------------
# MODEL_PATH = "models/lipnet_epoch_50.h5"

# # ---------------- VOCAB ----------------
# vocab = [x for x in "abcdefghijklmnopqrstuvwxyz'?!123456789 "]

# char_to_num = tf.keras.layers.StringLookup(vocabulary=vocab, oov_token="")
# num_to_char = tf.keras.layers.StringLookup(
#     vocabulary=char_to_num.get_vocabulary(),
#     oov_token="",
#     invert=True
# )

# # ---------------- LOAD VIDEO ----------------
# def load_video(path):
#     cap = cv2.VideoCapture(path)
#     frames = []

#     for _ in range(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))):
#         ret, frame = cap.read()
#         if not ret:
#             break

#         frame = tf.image.rgb_to_grayscale(frame)
#         frame = frame[190:236, 80:220, :]
#         frames.append(frame)

#     cap.release()

#     frames = tf.stack(frames)

#     # Pad or trim to 75 frames
#     if frames.shape[0] < 75:
#         pad = tf.zeros((75 - frames.shape[0], 46, 140, 1))
#         frames = tf.concat([frames, pad], axis=0)

#     frames = frames[:75]

#     mean = tf.math.reduce_mean(frames)
#     std = tf.math.reduce_std(tf.cast(frames, tf.float32))

#     frames = tf.cast((frames - mean), tf.float32) / (std + 1e-6)

#     return frames

# # ---------------- BUILD MODEL ----------------
# def build_model():
#     from tensorflow.keras.models import Sequential
#     from tensorflow.keras.layers import (
#         Conv3D, LSTM, Dense, Dropout,
#         Bidirectional, MaxPool3D,
#         Activation, TimeDistributed, Flatten
#     )

#     model = Sequential()

#     model.add(Conv3D(128, 3, input_shape=(75,46,140,1), padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(Conv3D(256, 3, padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(Conv3D(75, 3, padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(TimeDistributed(Flatten()))

#     model.add(Bidirectional(LSTM(128, return_sequences=True)))
#     model.add(Dropout(0.5))

#     model.add(Bidirectional(LSTM(128, return_sequences=True)))
#     model.add(Dropout(0.5))

#     model.add(Dense(len(vocab)+1, activation='softmax'))

#     model.load_weights(MODEL_PATH)

#     return model

# # ---------------- DECODE ----------------
# def decode_prediction(yhat):
#     decoded = tf.keras.backend.ctc_decode(
#         yhat,
#         input_length=[75],
#         greedy=True
#     )[0][0].numpy()

#     return tf.strings.reduce_join(
#         num_to_char(decoded[0])
#     ).numpy().decode("utf-8")

# # ---------------- INFERENCE ----------------
# def run_inference(video_path):
#     print("\n🎥 Running Lip Reading Inference...")

#     model = build_model()

#     frames = load_video(video_path)
#     frames = tf.expand_dims(frames, axis=0)

#     yhat = model.predict(frames, verbose=0)

#     prediction = decode_prediction(yhat)

#     print("\n👉 Predicted Text:", prediction)

#     return prediction

# # ---------------- MAIN ----------------
# if __name__ == "__main__":
    
#     # Give single video input
#     video_path = "data/s1/bbal8p.mpg"
    
#     run_inference(video_path)


# import tensorflow as tf
# from utils import load_video, num_to_char
# from modelutil import load_model

# def decode_prediction(yhat):
#     decoded = tf.keras.backend.ctc_decode(
#         yhat,
#         input_length=[75],
#         greedy=True
#     )[0][0].numpy()

#     return tf.strings.reduce_join(
#         num_to_char(decoded[0])
#     ).numpy().decode("utf-8")

# def run_inference(video_path):
#     print("\n🎥 Running Inference...")

#     model = load_model()

#     frames = load_video(video_path)
#     frames = tf.expand_dims(frames, axis=0)

#     yhat = model.predict(frames, verbose=0)

#     prediction = decode_prediction(yhat)

#     print("\n👉 Predicted Text:", prediction)

# if __name__ == "__main__":
#     run_inference("data/s1/bbal8p.mpg")

# import tensorflow as tf

# from utils import load_video, num_to_char
# from modelutil import load_model


# # ---------------- LOAD ALIGNMENT ----------------
# def load_alignment(path):
#     with open(path, 'r') as f:
#         lines = f.readlines()

#     tokens = []
#     for line in lines:
#         line = line.split()
#         if line[2] != 'sil':
#             tokens = [*tokens, ' ', line[2]]

#     return tf.strings.reduce_join(tokens)


# # ---------------- INFERENCE ----------------
# def run_inference(video_path):

#     model = load_model()

#     # extract filename
#     file_name = video_path.split('/')[-1].split('.')[0]

#     align_path = f"data/alignments/s1/{file_name}.align"

#     # load video
#     frames = load_video(video_path)

#     # load real text (GROUND TRUTH)
#     real_text = load_alignment(align_path)

#     # predict
#     yhat = model.predict(tf.expand_dims(frames, axis=0))

#     # decode prediction
#     decoded = tf.keras.backend.ctc_decode(
#         yhat,
#         input_length=[75],
#         greedy=True
#     )[0][0].numpy()

#     # ---------------- PRINT OUTPUT ----------------
#     print('\n' + '~'*100 + ' REAL TEXT')
#     print(real_text.numpy().decode('utf-8'))

#     print('\n' + '~'*100 + ' PREDICTIONS')
#     for sentence in decoded:
#         print(
#             tf.strings.reduce_join(num_to_char(sentence))
#             .numpy()
#             .decode('utf-8')
#         )


# # ---------------- MAIN ----------------
# if __name__ == "__main__":

#     video_path = "data/s1/bbal8p.mpg"

#     run_inference(video_path)

import os
import cv2
import tensorflow as tf
import numpy as np

# ---------------- VOCAB ----------------
vocab = [x for x in "abcdefghijklmnopqrstuvwxyz'?!123456789 "]

char_to_num = tf.keras.layers.StringLookup(vocabulary=vocab, oov_token="")
num_to_char = tf.keras.layers.StringLookup(
    vocabulary=char_to_num.get_vocabulary(),
    oov_token="",
    invert=True
)

# ---------------- LOAD VIDEO ----------------
def load_video(path):
    cap = cv2.VideoCapture(path)
    frames = []

    for _ in range(int(cap.get(cv2.CAP_PROP_FRAME_COUNT))):
        ret, frame = cap.read()
        if not ret:
            break

        frame = tf.image.rgb_to_grayscale(frame)
        frame = frame[190:236, 80:220, :]
        frames.append(frame)

    cap.release()

    frames = tf.stack(frames)

    # pad / trim to 75 frames
    if frames.shape[0] < 75:
        pad = tf.zeros((75 - frames.shape[0], 46, 140, 1))
        frames = tf.concat([frames, pad], axis=0)

    frames = frames[:75]

    mean = tf.math.reduce_mean(frames)
    std = tf.math.reduce_std(tf.cast(frames, tf.float32))

    frames = tf.cast((frames - mean), tf.float32) / (std + 1e-6)

    return frames

# ---------------- LOAD ALIGNMENT ----------------
def load_alignment(path):
    with open(path, 'r') as f:
        lines = f.readlines()

    tokens = []
    for line in lines:
        line = line.split()
        if line[2] != 'sil':
            tokens = [*tokens, ' ', line[2]]

    return tf.strings.reduce_join(tokens)

# ---------------- BUILD MODEL ----------------
# def build_model():
#     from tensorflow.keras.models import Sequential
#     from tensorflow.keras.layers import (
#         Conv3D, LSTM, Dense, Dropout,
#         Bidirectional, MaxPool3D,
#         Activation, TimeDistributed, Flatten
#     )

#     model = Sequential()

#     model.add(Conv3D(128, 3, input_shape=(75,46,140,1), padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(Conv3D(256, 3, padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(Conv3D(75, 3, padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(TimeDistributed(Flatten()))

#     model.add(Bidirectional(LSTM(128, return_sequences=True)))
#     model.add(Dropout(0.5))

#     model.add(Bidirectional(LSTM(128, return_sequences=True)))
#     model.add(Dropout(0.5))

#     model.add(Dense(len(vocab)+1, activation='softmax'))

#     model.load_weights("models/lipnet_epoch_50.h5")

#     return model

# def build_model():
#     from tensorflow.keras.models import Sequential
#     from tensorflow.keras.layers import (
#         Conv3D, LSTM, Dense, Dropout,
#         Bidirectional, MaxPool3D,
#         Activation, TimeDistributed, Flatten
#     )

#     model = Sequential()

#     # -------- SAME AS TRAINING --------
#     model.add(Conv3D(128, 3, input_shape=(75,46,140,1), padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(Conv3D(256, 3, padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(Conv3D(75, 3, padding='same'))
#     model.add(Activation('relu'))
#     model.add(MaxPool3D((1,2,2)))

#     model.add(TimeDistributed(Flatten()))

#     model.add(Bidirectional(LSTM(128, return_sequences=True)))
#     model.add(Dropout(0.5))

#     model.add(Bidirectional(LSTM(128, return_sequences=True)))
#     model.add(Dropout(0.5))

#     model.add(Dense(len(vocab)+1, activation='softmax'))

#     model.load_weights("models/lipnet_epoch_50.h5")

#     return model

def build_model():
    from tensorflow.keras.models import load_model

    model = load_model("models/lipnet_epoch_50.h5", compile=False)

    return model
# ---------------- MAIN INFERENCE ----------------
def run_inference(video_path):

    model = build_model()

    # extract filename
    file_name = video_path.split('/')[-1].split('.')[0]
    align_path = f"data/alignments/s1/{file_name}.align"

    # load data
    frames = load_video(video_path)
    real_text = load_alignment(align_path)

    # predict
    yhat = model.predict(tf.expand_dims(frames, axis=0))

    # decode
    decoded = tf.keras.backend.ctc_decode(
        yhat,
        input_length=[75],
        greedy=True
    )[0][0].numpy()

    # ---------------- PRINT OUTPUT ----------------
    print('\n' + '~'*100 + ' REAL TEXT')
    print(real_text.numpy().decode('utf-8'))

    print('\n' + '~'*100 + ' PREDICTIONS')
    for sentence in decoded:
        print(
            tf.strings.reduce_join(num_to_char(sentence))
            .numpy()
            .decode('utf-8')
        )

# ---------------- RUN ----------------
if __name__ == "__main__":

    video_path = "data/s1/bbal8p.mpg"
    run_inference(video_path)